Repository 09s-BobBurger/Zolang-server, pull requests merged in 2024-06, with the labels that each got.

#44 🚑BBB-136 2분마다 사용량 출력
  src/main/java/com/kcs/zolang/exception/ErrorCode.java
  src/main/java/com/kcs/zolang/service/WorkloadService.java
  src/main/java/com/kcs/zolang/utility/MonitoringUtil.java
Labels: fix, 채린

#46 🐛 빌드 및 웹훅 버그 수정
  src/main/java/com/kcs/zolang/controller/WebhookController.java
  src/main/java/com/kcs/zolang/domain/CICD.java
  src/main/java/com/kcs/zolang/domain/EnvironmentVariable.java
  src/main/java/com/kcs/zolang/domain/WebhookEvent.java
  src/main/java/com/kcs/zolang/dto/response/CICDDto.java
  src/main/java/com/kcs/zolang/dto/response/UserCICDDto.java
  src/main/java/com/kcs/zolang/exception/ErrorCode.java
  src/main/java/com/kcs/zolang/repository/BuildRepository.java
  src/main/java/com/kcs/zolang/repository/EnvVarRepository.java
  src/main/java/com/kcs/zolang/repository/WebhookEventRepository.java
  src/main/java/com/kcs/zolang/service/CICDService.java
  src/main/java/com/kcs/zolang/service/ClusterService.java
  src/main/java/com/kcs/zolang/utility/ClusterUtil.java
  zolang-clusterrole.yaml
  zolang-clusterrolebinding.yaml
  zolang-sa.yaml
  zolang-secret.yaml
Labels: bug, fix, 동겸

#47 🚑 사용자 별 Job Queue를 도입. 한 사용자의 n번 요청을 동시 처리하면서 발생하는 문제 해결
  src/main/java/com/kcs/zolang/config/AsyncConfig.java
  src/main/java/com/kcs/zolang/exception/ErrorCode.java
  src/main/java/com/kcs/zolang/utility/ClusterUtil.java
  src/main/java/com/kcs/zolang/utility/JobQueueUtility.java
Labels: bug, fix, 동겸

#48 🐛 Deployment, service가 제대로 생성되지 않던 버그 수정 / 로그인 시 이메일 null point exception 해결 / 유저 이메일 업데이트 api 구현
  Dockerfile
  src/main/java/com/kcs/zolang/controller/UserController.java
  src/main/java/com/kcs/zolang/domain/User.java
  src/main/java/com/kcs/zolang/security/service/CustomOauth2UserDetailService.java
  src/main/java/com/kcs/zolang/service/ClusterService.java
  src/main/java/com/kcs/zolang/service/UserService.java
  src/main/java/com/kcs/zolang/utility/ClusterUtil.java
Labels: bug, fix, 동겸

#49 BBB-140 0일 때 continue
  src/main/java/com/kcs/zolang/utility/MonitoringUtil.java
Labels: fix, 채린

#51 🚑 BBB-141 크론잡 마지막 실행시간 null 에러 fix
  src/main/java/com/kcs/zolang/dto/response/workload/ControllerCronJobDto.java
Labels: fix, 채린

#52 🚑BBB-142 NaN일 시, 0 처리
  src/main/java/com/kcs/zolang/service/UserUsageService.java
Labels: fix, 채린

#53 ✨ 사용자가 배포한 서비스의 https 통신을 위한 ClusterIssuer 추가
  src/main/java/com/kcs/zolang/service/ClusterService.java
  src/main/java/com/kcs/zolang/utility/ClusterUtil.java
  yaml/certification.yaml
  yaml/clusterIssuer.yaml
  yaml/deployment.yaml
  yaml/docker-daemon-deployment.yaml
  yaml/docker-daemon-service.yaml
  yaml/ingress-frontend.yaml
  yaml/ingress.yaml
  yaml/redis-deployment.yaml
  yaml/redis-service.yaml
  yaml/service.yaml
  yaml/zolang-clusterrole.yaml
  yaml/zolang-clusterrolebinding.yaml
  yaml/zolang-sa.yaml
  yaml/zolang-secret.yaml
Labels: feature, 동겸

#54 BBB-143 service ExternalIP 출력
  src/main/java/com/kcs/zolang/dto/response/network/ServiceListDto.java
Labels: fix, 채린

#55 ✨ CICD 등록 시 serviceDomain이 있다면 certificate를 생성하는 로직 구현
  src/main/java/com/kcs/zolang/service/ClusterService.java
  src/main/java/com/kcs/zolang/utility/ClusterUtil.java
Labels: feature, 동겸

#56 ✨ CICD 삭제 시 리소스 삭제 로직 구현 / ✨ 리포지토리 조회 페이징 고려처리 로직 추가 / 🐛 rollout 버그 수정 / ✨ 예외 처리
  src/main/java/com/kcs/zolang/dto/response/cluster/UserUsageDto.java
  src/main/java/com/kcs/zolang/exception/ErrorCode.java
  src/main/java/com/kcs/zolang/service/CICDService.java
  src/main/java/com/kcs/zolang/service/ClusterService.java
  src/main/java/com/kcs/zolang/service/GithubService.java
  src/main/java/com/kcs/zolang/service/NamespaceService.java
  src/main/java/com/kcs/zolang/service/NetworkService.java
  src/main/java/com/kcs/zolang/service/UserUsageService.java
  src/main/java/com/kcs/zolang/service/WorkloadService.java
  src/main/java/com/kcs/zolang/utility/ClusterUtil.java
Labels: feature, 동겸

#57 🚑BBB-144 중복 저장 처리
  src/main/java/com/kcs/zolang/repository/BillRepository.java
  src/main/java/com/kcs/zolang/repository/UsageRepository.java
  src/main/java/com/kcs/zolang/service/UserUsageService.java
Labels: fix, 채린

#58 🚑BBB-145 분산락 및 분산 처리
  src/main/java/com/kcs/zolang/utility/MonitoringUtil.java
Labels: fix, 채린
