Repository 09s-BobBurger/Zolang-server, pull requests merged in 2024-05, with the labels that each got.

#7 ✨ 클러스터 리스트 조회, 노드 리스트 및 상세 조회, 클러스터 접근에 필요한 CA 인증 로직 구현
  build.gradle
  src/main/java/com/kcs/zolang/controller/ClusterController.java
  src/main/java/com/kcs/zolang/domain/Cluster.java
  src/main/java/com/kcs/zolang/dto/request/RegisterClusterDto.java
  src/main/java/com/kcs/zolang/dto/response/ClusterListDto.java
  src/main/java/com/kcs/zolang/exception/ErrorCode.java
  src/main/java/com/kcs/zolang/repository/ClusterRepository.java
  src/main/java/com/kcs/zolang/service/ClusterService.java
  src/main/java/com/kcs/zolang/utility/ClusterApiUtil.java
Labels: feature, 동겸

#8 ✨ 노드 상세보기 API 구현 및 노드 리스트 조회 API 간소화
  src/main/java/com/kcs/zolang/controller/ClusterController.java
  src/main/java/com/kcs/zolang/exception/ErrorCode.java
  src/main/java/com/kcs/zolang/repository/UserRepository.java
  src/main/java/com/kcs/zolang/security/handler/login/Oauth2SuccessHandler.java
  src/main/java/com/kcs/zolang/service/ClusterService.java
Labels: feature, 동겸

#9 ✨ workload overview/pod list 조회 API 구현
  build.gradle
  src/main/java/com/kcs/zolang/constants/Constants.java
  src/main/java/com/kcs/zolang/controller/WorkloadController.java
  src/main/java/com/kcs/zolang/dto/global/ResponseDto.java
  src/main/java/com/kcs/zolang/dto/response/PodSimpleDto.java
  src/main/java/com/kcs/zolang/dto/response/SimpleOverviewDto.java
  src/main/java/com/kcs/zolang/dto/response/UserUrlTokenDto.java
  src/main/java/com/kcs/zolang/dto/response/WorkloadOverviewDto.java
  src/main/java/com/kcs/zolang/exception/ErrorCode.java
  src/main/java/com/kcs/zolang/security/handler/login/Oauth2SuccessHandler.java
  src/main/java/com/kcs/zolang/service/WorkloadService.java
  src/main/java/com/kcs/zolang/utility/MonitoringUtil.java
  src/main/resources/application.yml
Labels: feature, 채린

#11 ✨ BBB-68 파드 상세 조회 & Controller List
  build.gradle
  src/main/java/com/kcs/zolang/controller/WorkloadController.java
  src/main/java/com/kcs/zolang/dto/response/CommonControllerDto.java
  src/main/java/com/kcs/zolang/dto/response/ControllerCronJobDto.java
  src/main/java/com/kcs/zolang/dto/response/PodConditionsDto.java
  src/main/java/com/kcs/zolang/dto/response/PodControlledDto.java
  src/main/java/com/kcs/zolang/dto/response/PodDetailDto.java
  src/main/java/com/kcs/zolang/dto/response/PodMetadataDto.java
  src/main/java/com/kcs/zolang/dto/response/PodPersistentVolumeClaimDto.java
  src/main/java/com/kcs/zolang/dto/response/PodResourceDto.java
  src/main/java/com/kcs/zolang/dto/response/PodSimpleDto.java
  src/main/java/com/kcs/zolang/service/WorkloadService.java
  src/main/java/com/kcs/zolang/utility/MonitoringUtil.java
Labels: feature, 채린

#10 ✨ 로그인한 사용자의 리포지토리 조회, 브랜치 조회, 특정 내용 커밋 API 로직 구현 및 테스트 완료
  build.gradle
  src/main/java/com/kcs/zolang/controller/GithubController.java
  src/main/java/com/kcs/zolang/controller/UserController.java
  src/main/java/com/kcs/zolang/domain/User.java
  src/main/java/com/kcs/zolang/dto/request/CommitDto.java
  src/main/java/com/kcs/zolang/dto/response/ClusterListDto.java
  src/main/java/com/kcs/zolang/dto/response/GitBranchDto.java
  src/main/java/com/kcs/zolang/dto/response/GitRepoDto.java
  src/main/java/com/kcs/zolang/dto/response/UserDetailDto.java
  src/main/java/com/kcs/zolang/repository/UserRepository.java
  src/main/java/com/kcs/zolang/security/config/EncryptionConfig.java
  src/main/java/com/kcs/zolang/security/config/SecurityConfig.java
  src/main/java/com/kcs/zolang/security/handler/login/DefaultFailureHandler.java
  src/main/java/com/kcs/zolang/security/handler/login/DefaultSuccessHandler.java
  src/main/java/com/kcs/zolang/security/handler/login/Oauth2SuccessHandler.java
  src/main/java/com/kcs/zolang/security/handler/logout/CustomLogoutProcessHandler.java
  src/main/java/com/kcs/zolang/security/service/CustomOauth2UserDetailService.java
  src/main/java/com/kcs/zolang/service/ClusterService.java
  src/main/java/com/kcs/zolang/service/GithubService.java
  src/main/java/com/kcs/zolang/service/UserService.java
Labels: feature, 동겸

#13 ✨ BBB-81 특정 네임스페이스 컨트롤러 조회
  src/main/java/com/kcs/zolang/controller/WorkloadController.java
  src/main/java/com/kcs/zolang/dto/response/PodDetailDto.java
  src/main/java/com/kcs/zolang/service/WorkloadService.java
Labels: feature, 채린

#12 ✨ CD API 구현 완료 / EKS 환경 배포 완료
  Dockerfile
  clusterIssuer.yaml
  deployment.yaml
  ingress.yaml
  service.yaml
  src/main/java/com/kcs/zolang/config/RestTemplateConfig.java
  src/main/java/com/kcs/zolang/config/SwaggerConfig.java
  src/main/java/com/kcs/zolang/controller/CICDController.java
  src/main/java/com/kcs/zolang/controller/WebhookController.java
  src/main/java/com/kcs/zolang/domain/Build.java
  src/main/java/com/kcs/zolang/domain/CICD.java
  src/main/java/com/kcs/zolang/dto/request/CommitDto.java
  src/main/java/com/kcs/zolang/dto/request/GitRepoRequestDto.java
  src/main/java/com/kcs/zolang/dto/response/GitRepoDto.java
  src/main/java/com/kcs/zolang/exception/ErrorCode.java
  src/main/java/com/kcs/zolang/repository/CICDRepository.java
  src/main/java/com/kcs/zolang/service/CICDService.java
  src/main/java/com/kcs/zolang/service/GithubService.java
  src/main/resources/application.yml
Labels: feature, 동겸

#15 🚑 EKS 배포 환경에서 발생했던 에러 수정
  build.gradle
  deployment.yaml
  ingress.yaml
  redis-deployment.yaml
  redis-service.yaml
  src/main/java/com/kcs/zolang/config/CorsConfig.java
  src/main/java/com/kcs/zolang/config/RedisConfig.java
  src/main/java/com/kcs/zolang/constants/Constants.java
  src/main/java/com/kcs/zolang/security/handler/login/Oauth2SuccessHandler.java
  src/main/java/com/kcs/zolang/utility/CookieUtil.java
Labels: bug, 동겸

#14 ✨ BBB-75 pod 사용량 출력
  build.gradle
  src/main/java/com/kcs/zolang/ZolangApplication.java
  src/main/java/com/kcs/zolang/config/RedisConfig.java
  src/main/java/com/kcs/zolang/controller/AuthController.java
  src/main/java/com/kcs/zolang/controller/WorkloadController.java
  src/main/java/com/kcs/zolang/dto/response/PodContainerDto.java
  src/main/java/com/kcs/zolang/dto/response/PodContainerStateDto.java
  src/main/java/com/kcs/zolang/dto/response/PodDetailDto.java
  src/main/java/com/kcs/zolang/dto/response/PodListDto.java
  src/main/java/com/kcs/zolang/dto/response/PodSimpleDto.java
  src/main/java/com/kcs/zolang/dto/response/UsageDto.java
  src/main/java/com/kcs/zolang/dto/response/UserUrlTokenDto.java
  src/main/java/com/kcs/zolang/exception/ErrorCode.java
  src/main/java/com/kcs/zolang/repository/ClusterRepository.java
  src/main/java/com/kcs/zolang/service/WorkloadService.java
  src/main/java/com/kcs/zolang/utility/MonitoringUtil.java
Labels: feature, 채린

#17 🚑 서브도메인 적용 반영 및 Redis 설정 병합
  ingress.yaml
  src/main/java/com/kcs/zolang/config/RedisConfig.java
  src/main/java/com/kcs/zolang/config/SwaggerConfig.java
  src/main/java/com/kcs/zolang/exception/ErrorCode.java
  src/main/java/com/kcs/zolang/security/handler/login/Oauth2SuccessHandler.java
  src/main/java/com/kcs/zolang/service/ClusterService.java
  src/main/resources/application.yml
Labels: bug, 동겸

#18 ✨BBB-84 Pod Detail container
  src/main/java/com/kcs/zolang/config/RedisConfig.java
  src/main/java/com/kcs/zolang/dto/response/ContainerDto.java
  src/main/java/com/kcs/zolang/dto/response/EnvironmentVariableDto.java
  src/main/java/com/kcs/zolang/dto/response/MountDto.java
  src/main/java/com/kcs/zolang/dto/response/PodDetailDto.java
  src/main/java/com/kcs/zolang/dto/response/PodResourceDto.java
  src/main/java/com/kcs/zolang/dto/response/PodSimpleDto.java
  src/main/java/com/kcs/zolang/dto/response/SecurityContextDto.java
  src/main/java/com/kcs/zolang/exception/ErrorCode.java
  src/main/java/com/kcs/zolang/service/ClusterService.java
  src/main/java/com/kcs/zolang/service/WorkloadService.java
  src/main/java/com/kcs/zolang/utility/MonitoringUtil.java
Labels: feature, 채린

#19 ✨BBB-89 DeploymentDetail
  src/main/java/com/kcs/zolang/controller/WorkloadController.java
  src/main/java/com/kcs/zolang/dto/response/CommonMetadataDto.java
  src/main/java/com/kcs/zolang/dto/response/DeploymentConditionDto.java
  src/main/java/com/kcs/zolang/dto/response/DeploymentDetailDto.java
  src/main/java/com/kcs/zolang/dto/response/DeploymentPodStatusDto.java
  src/main/java/com/kcs/zolang/dto/response/DeploymentResourceDto.java
  src/main/java/com/kcs/zolang/dto/response/PodDetailDto.java
  src/main/java/com/kcs/zolang/dto/response/PodMetadataDto.java
  src/main/java/com/kcs/zolang/dto/response/RolingUpdateStrategyDto.java
  src/main/java/com/kcs/zolang/service/ClusterService.java
  src/main/java/com/kcs/zolang/service/WorkloadService.java
Labels: feature, 채린

#21 ✨BBB-91 demonSet,statefulSet, RefilcasSet detail
  src/main/java/com/kcs/zolang/controller/WorkloadController.java
  src/main/java/com/kcs/zolang/dto/response/CommonControllerDetailDto.java
  src/main/java/com/kcs/zolang/dto/response/CommonControllerPodStatusDto.java
  src/main/java/com/kcs/zolang/dto/response/CommonControllerResourceDto.java
  src/main/java/com/kcs/zolang/dto/response/CommonMetadataDto.java
  src/main/java/com/kcs/zolang/dto/response/DeploymentDetailDto.java
  src/main/java/com/kcs/zolang/dto/response/PodDetailDto.java
  src/main/java/com/kcs/zolang/dto/response/PodSimpleDto.java
  src/main/java/com/kcs/zolang/dto/response/ServiceDetailDto.java
  src/main/java/com/kcs/zolang/dto/response/ServiceListDto.java
  src/main/java/com/kcs/zolang/dto/response/network/ServiceDetailDto.java
  src/main/java/com/kcs/zolang/exception/ErrorCode.java
  src/main/java/com/kcs/zolang/service/NetworkService.java
  src/main/java/com/kcs/zolang/service/WorkloadService.java
Labels: feature, 채린

#24 🚑 BBB-101 controller null 오류
  src/main/java/com/kcs/zolang/service/WorkloadService.java
Labels: fix, 채린

#26 🚑 엔드포인트 오타 수정
  src/main/java/com/kcs/zolang/constants/Constants.java
  src/main/java/com/kcs/zolang/controller/UserController.java
  src/main/java/com/kcs/zolang/security/config/SecurityConfig.java
Labels: fix, 동겸

#27 🚑 BBB-106 해당 컨드롤러의 service 가져오는 로직 수정
  src/main/java/com/kcs/zolang/controller/WorkloadController.java
  src/main/java/com/kcs/zolang/dto/response/CommonControllerDetailDto.java
  src/main/java/com/kcs/zolang/dto/response/DeploymentDetailDto.java
  src/main/java/com/kcs/zolang/dto/response/RollingUpdateStrategyDto.java
  src/main/java/com/kcs/zolang/service/WorkloadService.java
Labels: fix, 채린

#25 🚑 BBB-102 Dto 변수명 바꾸기/Dto 파일 정리
  src/main/java/com/kcs/zolang/controller/WorkloadController.java
  src/main/java/com/kcs/zolang/dto/response/PodContainerDto.java
  src/main/java/com/kcs/zolang/dto/response/PodContainerStateDto.java
  src/main/java/com/kcs/zolang/dto/response/SimpleOverviewDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/CommonControllerDetailDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/CommonControllerDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/CommonControllerPodStatusDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/CommonControllerResourceDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/CommonMetadataDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/ContainerDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/ControllerCronJobDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/DeploymentConditionDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/DeploymentDetailDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/DeploymentPodStatusDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/DeploymentResourceDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/EnvironmentVariableDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/MountDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/PodConditionsDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/PodControlledDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/PodDetailDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/PodListDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/PodPersistentVolumeClaimDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/PodResourceDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/PodSimpleDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/RollingUpdateStrategyDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/SecurityContextDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/SimpleOverviewDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/UsageDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/WorkloadOverviewDto.java
  src/main/java/com/kcs/zolang/service/WorkloadService.java
  src/main/java/com/kcs/zolang/utility/MonitoringUtil.java
Labels: fix, 채린

#29 ✨ 클러스터 버전 조회 api 구현
  src/main/java/com/kcs/zolang/controller/ClusterController.java
  src/main/java/com/kcs/zolang/dto/request/ClusterVersionRequestDto.java
  src/main/java/com/kcs/zolang/service/ClusterService.java
Labels: feature, 동겸

#28 BBB-108 사용량 수집, 타임아웃 에러 무시
  src/main/java/com/kcs/zolang/service/WorkloadService.java
  src/main/java/com/kcs/zolang/utility/MonitoringUtil.java
Labels: fix, 채린

#30 BBB-107 job 리스트 구현
  src/main/java/com/kcs/zolang/dto/response/workload/JobSimpleDto.java
  src/main/java/com/kcs/zolang/service/WorkloadService.java
  src/main/java/com/kcs/zolang/utility/MonitoringUtil.java
Labels: feature, 채린

#36 ✨BBB-112 컨트롤러 Pod 사용량 조회 & 리스트 조회 페이징 처리
  src/main/java/com/kcs/zolang/controller/WorkloadController.java
  src/main/java/com/kcs/zolang/dto/response/workload/CommonControllerListDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/CronJobListDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/JobListDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/PodListDto.java
  src/main/java/com/kcs/zolang/dto/response/workload/PodMetricsDto.java
  src/main/java/com/kcs/zolang/service/WorkloadService.java
Labels: feature, 채린

#37 ✨ 배포 및 CICD 로직 구현 및 테스트 완료
  Dockerfile
  deployment.yaml
  src/main/java/com/kcs/zolang/constants/Constants.java
  src/main/java/com/kcs/zolang/controller/CICDController.java
  src/main/java/com/kcs/zolang/domain/CICD.java
  src/main/java/com/kcs/zolang/exception/ErrorCode.java
  src/main/java/com/kcs/zolang/service/CICDService.java
  src/main/java/com/kcs/zolang/service/ClusterService.java
  src/main/java/com/kcs/zolang/utility/ClusterUtil.java
Labels: feature, 동겸

#38 🚑BBB-122 pod 사용량 저장 로직 수정
  src/main/java/com/kcs/zolang/utility/MonitoringUtil.java
Labels: fix, 채린

#40 🐛 출력 버퍼 포화로 인한 Time Out 버그 수정 / ✨ CICD 및 빌드 기록 조회 api 구현
  deployment.yaml
  docker-daemon-deployment.yaml
  docker-daemon-service.yaml
  src/main/java/com/kcs/zolang/controller/CICDController.java
  src/main/java/com/kcs/zolang/controller/ClusterController.java
  src/main/java/com/kcs/zolang/domain/Build.java
  src/main/java/com/kcs/zolang/domain/Cluster.java
  src/main/java/com/kcs/zolang/dto/response/BuildDto.java
  src/main/java/com/kcs/zolang/dto/response/CICDDto.java
  src/main/java/com/kcs/zolang/dto/response/cluster/ClusterListDto.java
  src/main/java/com/kcs/zolang/repository/BuildRepository.java
  src/main/java/com/kcs/zolang/repository/CICDRepository.java
  src/main/java/com/kcs/zolang/repository/ClusterRepository.java
  src/main/java/com/kcs/zolang/service/CICDService.java
  src/main/java/com/kcs/zolang/service/ClusterService.java
  src/main/java/com/kcs/zolang/utility/ClusterUtil.java
  src/main/java/com/kcs/zolang/utility/MonitoringUtil.java
  tls.crt
  tls.key
Labels: bug, fix, 동겸
